Update nginx-app.yml

diff --git a/.github/workflows/nginx-app.yml b/.github/workflows/nginx-app.yml
--- a/.github/workflows/nginx-app.yml
+++ b/.github/workflows/nginx-app.yml
@@ -69,6 +69,33 @@ jobs:
          check_count=0
          success=false
 
+         while [ "$check_count" -lt "$max_checks" ]; do
+           sleep 45
+           deployment_status=$(check_deployment_status)
+
+           echo "Deployment Status: $deployment_status"
+
+           success=$(echo "$deployment_status" | jq -r '.success')
+
+           if [ "$success" == "true" ]; then
+             success=true
+             break
+           fi
+
+           desired_count=$(echo "$deployment_status" | jq -r '.desiredCount')
+           running_count=$(echo "$deployment_status" | jq -r '.runningCount')
+
+           echo "Check $((check_count + 1)) of $max_checks: Desired tasks: $desired_count, Running tasks: $running_count."
+           check_count=$((check_count + 1))
+         done
+
+         if [ "$success" == true ]; then
+           echo "ECS deployment was successful!"
+         else
+           echo "ECS deployment verification failed! Deployment was not completed successfully."
+           exit 1
+         fi         
+
          check_deployment_status() {
            service_info=$(aws ecs describe-services --cluster ${{ env.AWS_ECS_CLUSTER }} --services ${{ env.AWS_ECS_NGINX_SERVICE }} --query 'services[0].deployments[?status==`PRIMARY`]' --output json)
            primary_deployment=$(echo "$service_info" | jq -c '.[0]')
@@ -99,29 +126,4 @@ jobs:
            fi
          }
 
-         while [ "$check_count" -lt "$max_checks" ]; do
-           sleep 45
-           deployment_status=$(check_deployment_status)
 
-           echo "Deployment Status: $deployment_status"
-
-           success=$(echo "$deployment_status" | jq -r '.success')
-
-           if [ "$success" == "true" ]; then
-             success=true
-             break
-           fi
-
-           desired_count=$(echo "$deployment_status" | jq -r '.desiredCount')
-           running_count=$(echo "$deployment_status" | jq -r '.runningCount')
-
-           echo "Check $((check_count + 1)) of $max_checks: Desired tasks: $desired_count, Running tasks: $running_count."
-           check_count=$((check_count + 1))
-         done
-
-         if [ "$success" == true ]; then
-           echo "ECS deployment was successful!"
-         else
-           echo "ECS deployment verification failed! Deployment was not completed successfully."
-           exit 1
-         fi
